# Generated by Django 4.2.11 on 2024-05-13 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_second_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('customer_first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('customer_phone_number', models.CharField(max_length=13, unique=True, verbose_name='Номер телефону')),
                ('login', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Логін')),
                ('password', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Пароль')),
                ('role', models.CharField(choices=[('a', 'Замовник'), ('b', 'Адміністратор')], max_length=1, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['id'],
            },
        ),
    ]
